// FROM: https://teampilot.ai/team/tristan/chat/cljtv2rui000dmu08cl5ik9gb

export const taxonMappingByAI = [
  {
    ancestorId: 1,
    children: [
      {
        taxonId: 47120,
        name: "Arthropods",
        pokemon: "Krabby",
        count: 44675138,
      },
      {
        taxonId: 2,
        name: "Chordates",
        pokemon: "Pikachu",
        count: 33546115,
      },
      {
        taxonId: 47115,
        name: "Molluscs",
        pokemon: "Shellder",
        count: 2285621,
      },
      {
        taxonId: 47534,
        name: "Cnidarians",
        pokemon: "Tentacool",
        count: 386174,
      },
      {
        taxonId: 47549,
        name: "Echinoderms",
        pokemon: "Starmie",
        count: 276210,
      },
      {
        taxonId: 47491,
        name: "Segmented Worms",
        pokemon: "Wormadam",
        count: 195805,
      },
      {
        taxonId: 48824,
        name: "Sponges",
        pokemon: "Mareanie",
        count: 71786,
      },
      {
        taxonId: 52319,
        name: "Flatworms",
        pokemon: "Eelektrik",
        count: 53268,
      },
      {
        taxonId: 68104,
        name: "Bryozoans",
        pokemon: "Cradily",
        count: 24972,
      },
      {
        taxonId: 126917,
        name: "Rotifers",
        pokemon: "Rotom",
        count: 7161,
      },
      {
        taxonId: 51508,
        name: "Comb Jellies",
        pokemon: "Jellicent",
        count: 7076,
      },
      {
        taxonId: 54960,
        name: "Nematodes",
        pokemon: "Barboach",
        count: 7038,
      },
      {
        taxonId: 51280,
        name: "Ribbon Worms",
        pokemon: "Scolipede",
        count: 4298,
      },
      {
        taxonId: 63142,
        name: "Horsehair Worms",
        pokemon: "Wimpod",
        count: 3248,
      },
      {
        taxonId: 51836,
        name: "Velvet Worms",
        pokemon: "Venipede",
        count: 1851,
      },
      {
        taxonId: 124337,
        name: "Tardigrades",
        pokemon: "Pyukumuku",
        count: 1654,
      },
      {
        taxonId: 122158,
        name: "Brachiopods",
        pokemon: "Clamperl",
        count: 1425,
      },
      {
        taxonId: 48051,
        name: "Horseshoe Worms",
        pokemon: "Horsea",
        count: 628,
      },
      {
        taxonId: 151829,
        name: "Gastrotrichs",
        pokemon: "Trubbish",
        count: 625,
      },
      {
        taxonId: 211191,
        name: "Xenoturbellids & allies",
        pokemon: "Sandygast",
        count: 411,
      },
      {
        taxonId: 68235,
        name: "Hemichordates",
        pokemon: "Gastrodon",
        count: 288,
      },
      {
        taxonId: 151831,
        name: "Entoprocts",
        pokemon: "Probopass",
        count: 258,
      },
      {
        taxonId: 151827,
        name: "Arrow Worms",
        pokemon: "Beedrill",
        count: 140,
      },
      {
        taxonId: 151826,
        name: "Thorny-headed Worms",
        pokemon: "Weedle",
        count: 58,
      },
      {
        taxonId: 151838,
        name: "Priapulid Worms",
        pokemon: "Wurmple",
        count: 31,
      },
      {
        taxonId: 151832,
        name: "Mud Dragons",
        pokemon: "Gible",
        count: 15,
      },
      {
        taxonId: 151830,
        name: "Jaw Worms",
        pokemon: "Carvanha",
        count: 5,
      },
      {
        taxonId: 151837,
        name: "Placozoans",
        pokemon: "Ditto",
        count: 2,
      },
      {
        taxonId: 774624,
        name: "Dicyemids",
        pokemon: "Deoxys",
        count: 2,
      },
      {
        taxonId: 151836,
        name: "Orthonectids",
        pokemon: "Nincada",
        count: 1,
      },
      {
        taxonId: 151833,
        name: "Loriciferans",
        pokemon: "Shelmet",
        count: 0,
      },
      {
        taxonId: 884506,
        name: "Gnathiferans",
        pokemon: "Gnath",
        count: 0,
      },
      {
        taxonId: 151828,
        name: "Cycliophorans",
        pokemon: "Spinda",
        count: 0,
      },
    ],
  },
  {
    ancestorId: 355675,
    children: [
      {
        taxonId: 3,
        name: "Birds",
        pokemon: "Pidgey",
        count: 22452424,
      },
      {
        taxonId: 40151,
        name: "Mammals",
        pokemon: "Rattata",
        count: 3755796,
      },
      {
        taxonId: 26036,
        name: "Reptiles",
        pokemon: "Ekans",
        count: 3452823,
      },
      {
        taxonId: 20978,
        name: "Amphibians",
        pokemon: "Poliwag",
        count: 2080607,
      },
      {
        taxonId: 47178,
        name: "Ray-finned Fishes",
        pokemon: "Magikarp",
        count: 1625931,
      },
      {
        taxonId: 47273,
        name: "Elasmobranchs",
        pokemon: "Sharpedo",
        count: 94707,
      },
      {
        taxonId: 797045,
        name: "Jawless Fishes",
        pokemon: "Relicanth",
        count: 2335,
      },
      {
        taxonId: 60450,
        name: "Chimaeras",
        pokemon: "Huntail",
        count: 929,
      },
      {
        taxonId: 362002,
        name: "Dinosaurs",
        pokemon: "Tyrantrum",
        count: 357,
      },
      {
        taxonId: 85497,
        name: "Lobe-finned Fishes",
        pokemon: "Relicanth",
        count: 168,
      },
      {
        taxonId: 1365642,
        name: "Eupelycosauria",
        pokemon: "Salamence",
        count: 15,
      },
      {
        taxonId: 703470,
        name: "Dicynodonts",
        pokemon: "Cranidos",
        count: 14,
      },
      {
        taxonId: 714997,
        name: "Placoderms",
        pokemon: "Bastiodon",
        count: 10,
      },
      {
        taxonId: 1142569,
        name: "Pelycosauria",
        pokemon: "Tyranitar",
        count: 4,
      },
      {
        taxonId: 705887,
        name: "Anteosaurids",
        pokemon: "Tyrantrum",
        count: 2,
      },
      {
        taxonId: 1228051,
        name: "Diadectids",
        pokemon: "Kabuto",
        count: 0,
      },
    ],
  },
  {
    ancestorId: 3,
    children: [
      {
        taxonId: 7251,
        name: "Perching Birds",
        pokemon: "Pidgey",
        count: 10361897,
      },
      {
        taxonId: 6888,
        name: "Waterfowl",
        pokemon: "Psyduck",
        count: 2180631,
      },
      {
        taxonId: 67561,
        name: "Shorebirds and Allies",
        pokemon: "Wingull",
        count: 1970328,
      },
      {
        taxonId: 67566,
        name: "Pelicans, Herons, Ibises, and Allies",
        pokemon: "Pelipper",
        count: 1402633,
      },
      {
        taxonId: 71261,
        name: "Hawks, Eagles, Kites, and Allies",
        pokemon: "Braviary",
        count: 1191622,
      },
      {
        taxonId: 2708,
        name: "Pigeons and Doves",
        pokemon: "Pidgeot",
        count: 862639,
      },
      {
        taxonId: 17550,
        name: "Woodpeckers, Barbets, and Allies",
        pokemon: "Pikipek",
        count: 782554,
      },
      {
        taxonId: 67573,
        name: "Nightjars, Swifts, Hummingbirds, and Allies",
        pokemon: "Noctowl",
        count: 458634,
      },
      {
        taxonId: 4,
        name: "Cranes, Rails, and Allies",
        pokemon: "Cranidos",
        count: 428845,
      },
      {
        taxonId: 573,
        name: "Landfowl",
        pokemon: "Torchic",
        count: 372562,
      },
      {
        taxonId: 71268,
        name: "Gannets, Cormorants, and Allies",
        pokemon: "Cramorant",
        count: 363601,
      },
      {
        taxonId: 18874,
        name: "Parrots",
        pokemon: "Chatot",
        count: 303832,
      },
      {
        taxonId: 67570,
        name: "Falcons and Caracaras",
        pokemon: "Talonflame",
        count: 260573,
      },
      {
        taxonId: 19350,
        name: "Owls",
        pokemon: "Hoothoot",
        count: 239518,
      },
      {
        taxonId: 2114,
        name: "Kingfishers and Allies",
        pokemon: "Kingdra",
        count: 233709,
      },
      {
        taxonId: 559244,
        name: "New World Vultures",
        pokemon: "Mandibuzz",
        count: 211729,
      },
      {
        taxonId: 67563,
        name: "Grebes",
        pokemon: "Ducklett",
        count: 193737,
      },
      {
        taxonId: 1623,
        name: "Cuckoos",
        pokemon: "Murkrow",
        count: 124800,
      },
      {
        taxonId: 3726,
        name: "Storks",
        pokemon: "Swanna",
        count: 82237,
      },
      {
        taxonId: 67565,
        name: "Tubenoses",
        pokemon: "Probopass",
        count: 46578,
      },
      {
        taxonId: 525653,
        name: "Hornbills and Hoopoes",
        pokemon: "Toucannon",
        count: 44793,
      },
      {
        taxonId: 67562,
        name: "Loons",
        pokemon: "Lunatone",
        count: 44769,
      },
      {
        taxonId: 67569,
        name: "Flamingos",
        pokemon: "Flaaffy",
        count: 28561,
      },
      {
        taxonId: 20715,
        name: "Trogons and Quetzals",
        pokemon: "Tropius",
        count: 26685,
      },
      {
        taxonId: 67564,
        name: "Penguins",
        pokemon: "Piplup",
        count: 19663,
      },
      {
        taxonId: 71264,
        name: "Jacamars and Puffbirds",
        pokemon: "Pidgeotto",
        count: 11489,
      },
      {
        taxonId: 71266,
        name: "Bustards",
        pokemon: "Staraptor",
        count: 10016,
      },
      {
        taxonId: 20487,
        name: "Ostriches",
        pokemon: "Doduo",
        count: 7256,
      },
      {
        taxonId: 793433,
        name: "Turacos",
        pokemon: "Toucannon",
        count: 6518,
      },
      {
        taxonId: 367702,
        name: "Cassowaries and Emu",
        pokemon: "Dodrio",
        count: 5975,
      },
      {
        taxonId: 20530,
        name: "Tinamous",
        pokemon: "Starly",
        count: 5657,
      },
      {
        taxonId: 3686,
        name: "Mousebirds",
        pokemon: "Pikachu",
        count: 5454,
      },
      {
        taxonId: 470156,
        name: "Sandgrouse",
        pokemon: "Sandslash",
        count: 3301,
      },
      {
        taxonId: 367701,
        name: "Rheas",
        pokemon: "Rhydon",
        count: 3050,
      },
      {
        taxonId: 67567,
        name: "Tropicbirds",
        pokemon: "Tropius",
        count: 2943,
      },
      {
        taxonId: 508251,
        name: "Hoatzins",
        pokemon: "Ho-Oh",
        count: 1759,
      },
      {
        taxonId: 71262,
        name: "Seriemas",
        pokemon: "Serperior",
        count: 1621,
      },
      {
        taxonId: 71263,
        name: "Kagu and Sunbittern",
        pokemon: "Kakuna",
        count: 1086,
      },
      {
        taxonId: 367703,
        name: "Kiwis",
        pokemon: "Kiwawi",
        count: 760,
      },
      {
        taxonId: 71265,
        name: "Mesites",
        pokemon: "Mesprit",
        count: 111,
      },
      {
        taxonId: 525652,
        name: "Cuckoo-Rollers",
        pokemon: "Crobat",
        count: 108,
      },
      {
        taxonId: 372820,
        name: "Moa",
        pokemon: "Moltres",
        count: 50,
      },
      {
        taxonId: 570881,
        name: "Elephant Birds",
        pokemon: "Elekid",
        count: 11,
      },
      {
        taxonId: 1365651,
        name: "Confuciusornithiformes",
        pokemon: "Confagrigus",
        count: 0,
      },
    ],
  },
  {
    ancestorId: 848317,
    children: [
      {
        taxonId: 848320,
        name: "Placental Mammals",
        pokemon: "Snorlax",
        count: 3562662,
      },
      {
        taxonId: 848319,
        name: "Marsupials",
        pokemon: "Kangaskhan",
        count: 138825,
      },
    ],
  },
  {
    ancestorId: 848320,
    children: [
      {
        taxonId: 848324,
        name: "Ungulates, Carnivorans, and Allies",
        pokemon: "Stantler",
        count: 1993168,
      },
      {
        taxonId: 848323,
        name: "Primates, Rodents, and Allies",
        pokemon: "Rattata",
        count: 1491882,
      },
      {
        taxonId: 848322,
        name: "Armadillos, Sloths, and Anteaters",
        pokemon: "Sandshrew",
        count: 39648,
      },
      {
        taxonId: 848321,
        name: "Afromammals",
        pokemon: "Elephant",
        count: 30893,
      },
    ],
  },
  {
    ancestorId: 848324,
    children: [
      {
        taxonId: 41573,
        name: "Carnivorans",
        pokemon: "Arcanine",
        count: 921817,
      },
      {
        taxonId: 152870,
        name: "Even-toed Ungulates and Cetaceans",
        pokemon: "Stantler",
        count: 818612,
      },
      {
        taxonId: 40268,
        name: "Bats",
        pokemon: "Zubat",
        count: 112559,
      },
      {
        taxonId: 533971,
        name: "Shrews, Moles, Hedgehogs, and Allies",
        pokemon: "Sandshrew",
        count: 83349,
      },
      {
        taxonId: 43327,
        name: "Odd-toed Ungulates",
        pokemon: "Rapidash",
        count: 54639,
      },
      {
        taxonId: 43357,
        name: "Pangolins",
        pokemon: "Sandslash",
        count: 689,
      },
    ],
  },
  {
    ancestorId: 41573,
    children: [
      {
        taxonId: 42043,
        name: "Canids",
        pokemon: "Arcanine",
        count: 304517,
      },
      {
        taxonId: 41944,
        name: "Felids",
        pokemon: "Persian",
        count: 166536,
      },
      {
        taxonId: 41660,
        name: "Raccoons, Coatis, and Allies",
        pokemon: "Zigzagoon",
        count: 123581,
      },
      {
        taxonId: 372843,
        name: "Pinnipeds",
        pokemon: "Seel",
        count: 106724,
      },
      {
        taxonId: 41770,
        name: "Mustelids",
        pokemon: "Linoone",
        count: 94704,
      },
      {
        taxonId: 41636,
        name: "Bears",
        pokemon: "Ursaring",
        count: 57363,
      },
      {
        taxonId: 41871,
        name: "Skunks and Stink-badgers",
        pokemon: "Skuntank",
        count: 29304,
      },
      {
        taxonId: 41893,
        name: "Mongooses",
        pokemon: "Zangoose",
        count: 14112,
      },
      {
        taxonId: 41574,
        name: "Civets, Genets, and Oyans",
        pokemon: "Liepard",
        count: 6348,
      },
      {
        taxonId: 41884,
        name: "Hyaenas",
        pokemon: "Mightyena",
        count: 5500,
      },
      {
        taxonId: 71376,
        name: "Red Pandas",
        pokemon: "Spinda",
        count: 843,
      },
      {
        taxonId: 71386,
        name: "Euplerids",
        pokemon: "Purrloin",
        count: 322,
      },
      {
        taxonId: 71394,
        name: "African Palm-civets",
        pokemon: "Watchog",
        count: 105,
      },
      {
        taxonId: 71397,
        name: "Linsangs",
        pokemon: "Sneasel",
        count: 11,
      },
    ],
  },
  {
    ancestorId: 152870,
    children: [
      {
        taxonId: 424850,
        name: "Ruminants",
        pokemon: "Stantler",
        count: 670828,
      },
      {
        taxonId: 925158,
        name: "Cetaceans and Hippopotamuses",
        pokemon: "Wailord",
        count: 81129,
      },
      {
        taxonId: 848343,
        name: "Suids and Peccaries",
        pokemon: "Emboar",
        count: 51520,
      },
      {
        taxonId: 925150,
        name: "Tylopodans",
        pokemon: "Camerupt",
        count: 12763,
      },
    ],
  },
  {
    ancestorId: 424850,
    children: [
      {
        taxonId: 42158,
        name: "Deer",
        pokemon: "Stantler",
        count: 445206,
      },
      {
        taxonId: 42241,
        name: "Bovids",
        pokemon: "Tauros",
        count: 198469,
      },
      {
        taxonId: 42153,
        name: "Giraffes and Okapi",
        pokemon: "Girafarig",
        count: 12998,
      },
      {
        taxonId: 42427,
        name: "Pronghorns",
        pokemon: "Stantler",
        count: 12440,
      },
      {
        taxonId: 42103,
        name: "Chevrotains",
        pokemon: "Deerling",
        count: 523,
      },
      {
        taxonId: 42140,
        name: "Musk Deer",
        pokemon: "Stantler",
        count: 91,
      },
    ],
  },
  {
    ancestorId: 848323,
    children: [
      {
        taxonId: 43698,
        name: "Rodents",
        pokemon: "Raticate",
        count: 1010139,
      },
      {
        taxonId: 43094,
        name: "Lagomorphs",
        pokemon: "Bunnelby",
        count: 260413,
      },
      {
        taxonId: 43367,
        name: "Primates",
        pokemon: "Aipom",
        count: 218095,
      },
      {
        taxonId: 46280,
        name: "Treeshrews",
        pokemon: "Emolga",
        count: 1329,
      },
      {
        taxonId: 42535,
        name: "Colugos",
        pokemon: "Gliscor",
        count: 1124,
      },
    ],
  },
  {
    ancestorId: 43698,
    children: [
      {
        taxonId: 129411,
        name: "Squirrels, Dormice, and Mountain Beavers",
        pokemon: "Pachirisu",
        count: 696207,
      },
      {
        taxonId: 870778,
        name: "Mice, Rats, and Hamsters",
        pokemon: "Rattata",
        count: 157517,
      },
      {
        taxonId: 870765,
        name: "Ctenohystricans",
        pokemon: "Bibarel",
        count: 74041,
      },
      {
        taxonId: 870764,
        name: "Beavers, Pocket Gophers, and Allies",
        pokemon: "Bidoof",
        count: 71176,
      },
      {
        taxonId: 870763,
        name: "Anomalures and Springhares",
        pokemon: "Diggersby",
        count: 329,
      },
    ],
  },
  {
    ancestorId: 848321,
    children: [
      {
        taxonId: 43691,
        name: "Proboscideans",
        pokemon: "Donphan",
        count: 17584,
      },
      {
        taxonId: 46306,
        name: "Sirenians",
        pokemon: "Lapras",
        count: 6157,
      },
      {
        taxonId: 43083,
        name: "Hyraxes",
        pokemon: "Diggersby",
        count: 5189,
      },
      {
        taxonId: 42434,
        name: "Golden Moles and Tenrecs",
        pokemon: "Excadrill",
        count: 812,
      },
      {
        taxonId: 47059,
        name: "Aardvarks",
        pokemon: "Sandslash",
        count: 647,
      },
      {
        taxonId: 43208,
        name: "Sengis",
        pokemon: "Watchog",
        count: 503,
      },
    ],
  },
  {
    ancestorId: 26036,
    children: [
      {
        taxonId: 26172,
        name: "Squamata",
        pokemon: "Ekans",
        count: 2717001,
      },
      {
        taxonId: 39532,
        name: "Testudines",
        pokemon: "Squirtle",
        count: 647504,
      },
      {
        taxonId: 26039,
        name: "Crocodylia",
        pokemon: "Totodile",
        count: 84686,
      },
      {
        taxonId: 26162,
        name: "Rhynchocephalia",
        pokemon: "Sceptile",
        count: 1596,
      },
      {
        taxonId: 546667,
        name: "Sauropterygia",
        pokemon: "Lapras",
        count: 11,
      },
      {
        taxonId: 523017,
        name: "Ornithocheiroidea",
        pokemon: "Aerodactyl",
        count: 4,
      },
    ],
  },
  {
    ancestorId: 20978,
    children: [
      {
        taxonId: 20979,
        name: "Frogs and Toads",
        pokemon: "Poliwag",
        count: 1608155,
      },
      {
        taxonId: 26718,
        name: "Salamanders",
        pokemon: "Charmander",
        count: 465599,
      },
      {
        taxonId: 27880,
        name: "Caecilians",
        pokemon: "Ekans",
        count: 1417,
      },
    ],
  },
  {
    ancestorId: 47178,
    children: [
      {
        taxonId: 47233,
        name: "Perch-like Fishes",
        pokemon: "Magikarp",
        count: 284706,
      },
      {
        taxonId: 1303726,
        name: "Butterflyfishes, Angelfishes, and Allies",
        pokemon: "Goldeen",
        count: 231754,
      },
      {
        taxonId: 1303731,
        name: "Freshwater Sunfishes, Grunters, and Allies",
        pokemon: "Staryu",
        count: 151169,
      },
      {
        taxonId: 49216,
        name: "Minnows, Suckers, Carps, and Loaches",
        pokemon: "Barboach",
        count: 144394,
      },
      {
        taxonId: 1303736,
        name: "Cichlids, Damselfishes, and Allies",
        pokemon: "Seaking",
        count: 124032,
      },
      {
        taxonId: 47177,
        name: "Puffers and Filefishes",
        pokemon: "Qwilfish",
        count: 88557,
      },
      {
        taxonId: 47245,
        name: "Pipefishes and Allies",
        pokemon: "Horsea",
        count: 59225,
      },
      {
        taxonId: 1303727,
        name: "Barracudas, Jacks, Remoras, Flounders, Billfishes, and Allies",
        pokemon: "Sharpedo",
        count: 57737,
      },
      {
        taxonId: 1303725,
        name: "Gobies and allies",
        pokemon: "Finneon",
        count: 56675,
      },
      {
        taxonId: 49333,
        name: "Rivulines, Killifishes, and Livebearers",
        pokemon: "Feebas",
        count: 44799,
      },
      {
        taxonId: 49175,
        name: "Catfishes",
        pokemon: "Whiscash",
        count: 43828,
      },
      {
        taxonId: 1303737,
        name: "Blennies",
        pokemon: "Alomomola",
        count: 43751,
      },
      {
        taxonId: 47521,
        name: "Salmons, Trouts, and Whitefishes",
        pokemon: "Gyarados",
        count: 42375,
      },
      {
        taxonId: 1124233,
        name: "Tarpons, Eels, and Allies",
        pokemon: "Eelektrik",
        count: 36921,
      },
      {
        taxonId: 49235,
        name: "Herrings",
        pokemon: "Remoraid",
        count: 15671,
      },
      {
        taxonId: 85529,
        name: "Mullets",
        pokemon: "Basculin",
        count: 15283,
      },
      {
        taxonId: 1303741,
        name: "Cardinalfishes, nurseryfishes, and sanddivers",
        pokemon: "Luvdisc",
        count: 12763,
      },
      {
        taxonId: 47388,
        name: "Characins",
        pokemon: "Carvanha",
        count: 12695,
      },
      {
        taxonId: 51368,
        name: "Pikes and Mudminnows",
        pokemon: "Pikachu",
        count: 11579,
      },
      {
        taxonId: 51485,
        name: "Needlefishes, Halfbeaks, and Allies",
        pokemon: "Marill",
        count: 10967,
      },
      {
        taxonId: 1303739,
        name: "Mackerels, Tunas, Butterfishes, and Allies",
        pokemon: "Tynamo",
        count: 10803,
      },
      {
        taxonId: 1303738,
        name: "Leaffishes, Snakeheads, and Gouramis",
        pokemon: "Lombre",
        count: 9586,
      },
      {
        taxonId: 54544,
        name: "Gars",
        pokemon: "Feraligatr",
        count: 8198,
      },
      {
        taxonId: 1303734,
        name: "Squirrelfishes and soldierfishes",
        pokemon: "Corphish",
        count: 8150,
      },
      {
        taxonId: 85506,
        name: "Silversides",
        pokemon: "Chinchou",
        count: 8056,
      },
      {
        taxonId: 49409,
        name: "Grinners, Lizardfishes, and Allies",
        pokemon: "Eelektross",
        count: 7211,
      },
      {
        taxonId: 61542,
        name: "Anglerfishes",
        pokemon: "Lanturn",
        count: 6865,
      },
      {
        taxonId: 1303732,
        name: "Oceanic Basses",
        pokemon: "Relicanth",
        count: 6184,
      },
      {
        taxonId: 63741,
        name: "Cods",
        pokemon: "Wailmer",
        count: 5073,
      },
      {
        taxonId: 67410,
        name: "Clingfishes",
        pokemon: "Octillery",
        count: 4745,
      },
      {
        taxonId: 51373,
        name: "Toadfishes",
        pokemon: "Seismitoad",
        count: 3610,
      },
      {
        taxonId: 49824,
        name: "Sturgeons and Paddlefishes",
        pokemon: "Lapras",
        count: 2551,
      },
      {
        taxonId: 1303728,
        name: "Galaxiids",
        pokemon: "Starmie",
        count: 2307,
      },
      {
        taxonId: 49240,
        name: "Bonytongues",
        pokemon: "Arceus",
        count: 2085,
      },
      {
        taxonId: 53512,
        name: "Swamp Eels",
        pokemon: "Eelektross",
        count: 1546,
      },
      {
        taxonId: 58613,
        name: "Bowfins",
        pokemon: "Basculin",
        count: 1443,
      },
      {
        taxonId: 49887,
        name: "Smelts and Allies",
        pokemon: "Feebas",
        count: 1139,
      },
      {
        taxonId: 1303735,
        name: "Lanterneyes, fangtooths and allies",
        pokemon: "Lanturn",
        count: 942,
      },
      {
        taxonId: 85536,
        name: "Trout-perches, Pirate Perches, and Cavefishes",
        pokemon: "Barboach",
        count: 933,
      },
      {
        taxonId: 47391,
        name: "Cusk-eels",
        pokemon: "Eelektrik",
        count: 622,
      },
      {
        taxonId: 52559,
        name: "Neotropical Knifefishes",
        pokemon: "Pikachu",
        count: 474,
      },
      {
        taxonId: 55540,
        name: "Milkfishes",
        pokemon: "Milotic",
        count: 366,
      },
      {
        taxonId: 64602,
        name: "Dories",
        pokemon: "Sharpedo",
        count: 309,
      },
      {
        taxonId: 1303742,
        name: "Mooneyes",
        pokemon: "Lunatone",
        count: 294,
      },
      {
        taxonId: 85547,
        name: "Dragonfishes and Allies",
        pokemon: "Dragonair",
        count: 222,
      },
      {
        taxonId: 85540,
        name: "Bichirs",
        pokemon: "Milotic",
        count: 215,
      },
      {
        taxonId: 85530,
        name: "Lanternfishes",
        pokemon: "Lanturn",
        count: 172,
      },
      {
        taxonId: 49627,
        name: "Sawbellies",
        pokemon: "Sharpedo",
        count: 161,
      },
      {
        taxonId: 47513,
        name: "Velifers, Opahs, and Ribbonfishes",
        pokemon: "Gyarados",
        count: 157,
      },
      {
        taxonId: 1313092,
        name: "Blowhole perch",
        pokemon: "Relicanth",
        count: 55,
      },
      {
        taxonId: 1303729,
        name: "Marine Smelts",
        pokemon: "Feebas",
        count: 54,
      },
      {
        taxonId: 1303733,
        name: "Slickheads and tubeshoulders",
        pokemon: "Eelektrik",
        count: 50,
      },
      {
        taxonId: 85505,
        name: "Jellynose Fishes",
        pokemon: "Tentacool",
        count: 12,
      },
      {
        taxonId: 85542,
        name: "Swallowers and Gulpers",
        pokemon: "Gulpin",
        count: 12,
      },
      {
        taxonId: 85539,
        name: "Beardfishes",
        pokemon: "Beartic",
        count: 9,
      },
      {
        taxonId: 1194087,
        name: "Pycnodontiformes",
        pokemon: "Relicanth",
        count: 2,
      },
      {
        taxonId: 123589,
        name: "Aethalionopsis",
        pokemon: "No Pokemon Equivalent",
        count: 0,
      },
      {
        taxonId: 1389546,
        name: "Aesopichthyidae",
        pokemon: "No Pokemon Equivalent",
        count: 0,
      },
      {
        taxonId: 1227774,
        name: "Aspidorhynchiformes",
        pokemon: "No Pokemon Equivalent",
        count: 0,
      },
      {
        taxonId: 1303730,
        name: "Salamanderfishes",
        pokemon: "Wooper",
        count: 0,
      },
      {
        taxonId: 1303740,
        name: "Tube-Eyes",
        pokemon: "No Pokemon Equivalent",
        count: 0,
      },
      {
        taxonId: 471368,
        name: "Pycnodus",
        pokemon: "No Pokemon Equivalent",
        count: 0,
      },
    ],
  },
  {
    ancestorId: 47120,
    children: [
      {
        taxonId: 372739,
        name: "Hexapods",
        pokemon: "Scyther",
        count: 38976297,
      },
      {
        taxonId: 245097,
        name: "Chelicerates",
        pokemon: "Ariados",
        count: 4327304,
      },
      {
        taxonId: 85493,
        name: "Crustaceans",
        pokemon: "Krabby",
        count: 926770,
      },
      {
        taxonId: 144128,
        name: "Myriapods",
        pokemon: "Scolipede",
        count: 462832,
      },
      {
        taxonId: 205907,
        name: "Trilobites",
        pokemon: "Kabuto",
        count: 295,
      },
      {
        taxonId: 333781,
        name: "Dinocarididans",
        pokemon: "Kabutops",
        count: 8,
      },
    ],
  },
  {
    ancestorId: 372739,
    children: [
      {
        taxonId: 47158,
        name: "Insects",
        pokemon: "Beedrill",
        count: 38895116,
      },
      {
        taxonId: 243773,
        name: "Entognathans",
        pokemon: "Venonat",
        count: 82954,
      },
    ],
  },
  {
    ancestorId: 47158,
    children: [
      {
        taxonId: 184884,
        name: "Winged and Once-winged Insects",
        pokemon: "Butterfree",
        count: 38705313,
      },
      {
        taxonId: 48301,
        name: "Silverfishes",
        pokemon: "Durant",
        count: 26529,
      },
      {
        taxonId: 461443,
        name: "Bristletails",
        pokemon: "Kabuto",
        count: 12716,
      },
    ],
  },
  {
    ancestorId: 184884,
    children: [
      {
        taxonId: 47157,
        name: "Butterflies and Moths",
        pokemon: "Butterfree",
        count: 16100161,
      },
      {
        taxonId: 47208,
        name: "Beetles",
        pokemon: "Heracross",
        count: 5319211,
      },
      {
        taxonId: 47201,
        name: "Ants, Bees, Wasps, and Sawflies",
        pokemon: "Beedrill",
        count: 4889457,
      },
      {
        taxonId: 47744,
        name: "True Bugs, Hoppers, Aphids, and allies",
        pokemon: "Ariados",
        count: 3507776,
      },
      {
        taxonId: 47822,
        name: "Flies",
        pokemon: "Yanma",
        count: 3299651,
      },
      {
        taxonId: 47792,
        name: "Dragonflies and Damselflies",
        pokemon: "Yanmega",
        count: 2466252,
      },
      {
        taxonId: 47651,
        name: "Grasshoppers, Crickets, and Katydids",
        pokemon: "Kricketune",
        count: 1629739,
      },
      {
        taxonId: 48112,
        name: "Mantises",
        pokemon: "Scyther",
        count: 312230,
      },
      {
        taxonId: 48763,
        name: "Antlions, Lacewings, and Allies",
        pokemon: "Trapinch",
        count: 224681,
      },
      {
        taxonId: 81769,
        name: "Cockroaches and Termites",
        pokemon: "Durant",
        count: 223837,
      },
      {
        taxonId: 62164,
        name: "Caddisflies",
        pokemon: "Masquerain",
        count: 126831,
      },
      {
        taxonId: 48011,
        name: "Mayflies",
        pokemon: "Nincada",
        count: 106141,
      },
      {
        taxonId: 47198,
        name: "Stick Insects",
        pokemon: "Leavanny",
        count: 104749,
      },
      {
        taxonId: 47793,
        name: "Earwigs",
        pokemon: "Forretress",
        count: 81065,
      },
      {
        taxonId: 47504,
        name: "Stoneflies",
        pokemon: "Armaldo",
        count: 48769,
      },
      {
        taxonId: 83187,
        name: "Barklice, Booklice, and Parasitic Lice",
        pokemon: "Shuckle",
        count: 47273,
      },
      {
        taxonId: 47864,
        name: "Alderflies, Dobsonflies, and Fishflies",
        pokemon: "Surskit",
        count: 45399,
      },
      {
        taxonId: 49369,
        name: "Scorpionflies, Hangingflies, and Allies",
        pokemon: "Gligar",
        count: 37213,
      },
      {
        taxonId: 83201,
        name: "Thrips",
        pokemon: "Nincada",
        count: 15368,
      },
      {
        taxonId: 47794,
        name: "Snakeflies",
        pokemon: "Flygon",
        count: 13765,
      },
      {
        taxonId: 56834,
        name: "Webspinners",
        pokemon: "Spinarak",
        count: 5542,
      },
      {
        taxonId: 83204,
        name: "Fleas",
        pokemon: "Joltik",
        count: 1901,
      },
      {
        taxonId: 83202,
        name: "Twisted-wing Insects",
        pokemon: "Vibrava",
        count: 659,
      },
      {
        taxonId: 53795,
        name: "Ice Crawlers and Heelwalkers",
        pokemon: "Sneasel",
        count: 112,
      },
      {
        taxonId: 83200,
        name: "Angel Insects",
        pokemon: "Beautifly",
        count: 37,
      },
    ],
  },
  {
    ancestorId: 47208,
    children: [
      {
        taxonId: 71130,
        name: "Polyphaga",
        pokemon: "Heracross",
        count: 4761187,
      },
      {
        taxonId: 340471,
        name: "Adephaga",
        pokemon: "Kabuto",
        count: 460035,
      },
      {
        taxonId: 340473,
        name: "Archostemata",
        pokemon: "Pinsir",
        count: 789,
      },
      {
        taxonId: 340472,
        name: "Myxophaga",
        pokemon: "Surskit",
        count: 12,
      },
    ],
  },
  {
    ancestorId: 47201,
    children: [
      {
        taxonId: 124417,
        name: "Apocrita",
        pokemon: "Beedrill",
        count: 4676184,
      },
      {
        taxonId: 84643,
        name: "Symphyta",
        pokemon: "Pinsir",
        count: 169985,
      },
      {
        taxonId: 1429119,
        name: "Celliformidae",
        pokemon: "Weedle",
        count: 1,
      },
    ],
  },
  {
    ancestorId: 124417,
    children: [
      {
        taxonId: 326777,
        name: "Aculeata",
        pokemon: "Beedrill",
        count: 4084672,
      },
      {
        taxonId: 47200,
        name: "Ichneumonoidea",
        pokemon: "Beedrill",
        count: 284153,
      },
      {
        taxonId: 981280,
        name: "Proctotrupomorpha",
        pokemon: "Beedrill",
        count: 268600,
      },
      {
        taxonId: 145377,
        name: "Evanioidea",
        pokemon: "Beedrill",
        count: 17571,
      },
      {
        taxonId: 198947,
        name: "Stephanoidea",
        pokemon: "Beedrill",
        count: 1308,
      },
      {
        taxonId: 203217,
        name: "Ceraphronoidea",
        pokemon: "Beedrill",
        count: 900,
      },
      {
        taxonId: 342821,
        name: "Trigonaloidea",
        pokemon: "Beedrill",
        count: 399,
      },
      {
        taxonId: 342817,
        name: "Megalyroidea",
        pokemon: "Beedrill",
        count: 57,
      },
    ],
  },
  {
    ancestorId: 245097,
    children: [
      {
        taxonId: 47119,
        name: "Arachnida",
        pokemon: "Ariados",
        count: 4311573,
      },
      {
        taxonId: 48309,
        name: "Merostomata",
        pokemon: "Krabby",
        count: 13813,
      },
      {
        taxonId: 47825,
        name: "Pycnogonida",
        pokemon: "Octillery",
        count: 1712,
      },
    ],
  },
  {
    ancestorId: 47119,
    children: [
      {
        taxonId: 47118,
        name: "Spiders",
        pokemon: "Ariados",
        count: 3738760,
      },
      {
        taxonId: 52788,
        name: "Mites and Ticks",
        pokemon: "Joltik",
        count: 234464,
      },
      {
        taxonId: 47367,
        name: "Harvestmen",
        pokemon: "Galvantula",
        count: 194253,
      },
      {
        taxonId: 48894,
        name: "Scorpions",
        pokemon: "Skorupi",
        count: 86779,
      },
      {
        taxonId: 172373,
        name: "Pseudoscorpions",
        pokemon: "Gliscor",
        count: 13828,
      },
      {
        taxonId: 47824,
        name: "Solifuges",
        pokemon: "Scolipede",
        count: 13538,
      },
      {
        taxonId: 49722,
        name: "Tailless Whipscorpions",
        pokemon: "Whiscash",
        count: 10113,
      },
      {
        taxonId: 48900,
        name: "Whipscorpions",
        pokemon: "Whiscash",
        count: 5304,
      },
      {
        taxonId: 54730,
        name: "Shorttailed Whipscorpions",
        pokemon: "Whiscash",
        count: 335,
      },
      {
        taxonId: 129765,
        name: "Hooded Tickspiders",
        pokemon: "Ariados",
        count: 58,
      },
      {
        taxonId: 129764,
        name: "Micro Whipscorpions",
        pokemon: "Whiscash",
        count: 29,
      },
    ],
  },
  {
    ancestorId: 85493,
    children: [
      {
        taxonId: 473790,
        name: "Typical Crustaceans",
        pokemon: "Krabby",
        count: 909862,
      },
      {
        taxonId: 60395,
        name: "Branchiopods",
        pokemon: "Kabuto",
        count: 11278,
      },
      {
        taxonId: 473792,
        name: "Oligostracans",
        pokemon: "Omanyte",
        count: 3708,
      },
      {
        taxonId: 144130,
        name: "Remipedes",
        pokemon: "Anorith",
        count: 7,
      },
      {
        taxonId: 144129,
        name: "Horseshoe Shrimps",
        pokemon: "Corphish",
        count: 1,
      },
    ],
  },
  {
    ancestorId: 473790,
    children: [
      {
        taxonId: 47187,
        name: "Malacostraca",
        pokemon: "Krabby",
        count: 832449,
      },
      {
        taxonId: 1091452,
        name: "Hexanauplia",
        pokemon: "Octillery",
        count: 76837,
      },
    ],
  },
  {
    ancestorId: 47187,
    children: [
      {
        taxonId: 774775,
        name: "Decapods, Isopods, and allies",
        pokemon: "Krabby",
        count: 828630,
      },
      {
        taxonId: 774772,
        name: "Mantis Shrimps",
        pokemon: "Clawitzer",
        count: 3535,
      },
      {
        taxonId: 774771,
        name: "Leptostracans",
        pokemon: "Kabuto",
        count: 56,
      },
      {
        taxonId: 1366123,
        name: "Canadaspidida",
        pokemon: "Kabutops",
        count: 0,
      },
    ],
  },
  {
    ancestorId: 144128,
    children: [
      {
        taxonId: 47735,
        name: "Millipedes",
        pokemon: "Scolipede",
        count: 327686,
      },
      {
        taxonId: 49556,
        name: "Centipedes",
        pokemon: "Centiskorch",
        count: 132516,
      },
      {
        taxonId: 84638,
        name: "Symphylans",
        pokemon: "Nincada",
        count: 1636,
      },
      {
        taxonId: 83243,
        name: "Pauropodans",
        pokemon: "Venipede",
        count: 285,
      },
    ],
  },
  // {
  //   ancestorId: 1111111111111111111,
  //   children: null,
  // },
]
