export const taxonMapping = [
  {
    taxonId: 47120,
    name: "Arthropods",
    pokemon: "Krabby",
    count: 44675138,
  },
  {
    taxonId: 2,
    name: "Chordates",
    pokemon: "Pikachu",
    count: 33546115,
  },
  {
    taxonId: 47115,
    name: "Molluscs",
    pokemon: "Shellder",
    count: 2285621,
  },
  {
    taxonId: 47534,
    name: "Cnidarians",
    pokemon: "Tentacool",
    count: 386174,
  },
  {
    taxonId: 47549,
    name: "Echinoderms",
    pokemon: "Starmie",
    count: 276210,
  },
  {
    taxonId: 47491,
    name: "Segmented Worms",
    pokemon: "Wormadam",
    count: 195805,
  },
  {
    taxonId: 48824,
    name: "Sponges",
    pokemon: "Mareanie",
    count: 71786,
  },
  {
    taxonId: 52319,
    name: "Flatworms",
    pokemon: "Eelektrik",
    count: 53268,
  },
  {
    taxonId: 68104,
    name: "Bryozoans",
    pokemon: "Cradily",
    count: 24972,
  },
  {
    taxonId: 126917,
    name: "Rotifers",
    pokemon: "Rotom",
    count: 7161,
  },
  {
    taxonId: 51508,
    name: "Comb Jellies",
    pokemon: "Jellicent",
    count: 7076,
  },
  {
    taxonId: 54960,
    name: "Nematodes",
    pokemon: "Barboach",
    count: 7038,
  },
  {
    taxonId: 51280,
    name: "Ribbon Worms",
    pokemon: "Scolipede",
    count: 4298,
  },
  {
    taxonId: 63142,
    name: "Horsehair Worms",
    pokemon: "Wimpod",
    count: 3248,
  },
  {
    taxonId: 51836,
    name: "Velvet Worms",
    pokemon: "Venipede",
    count: 1851,
  },
  {
    taxonId: 124337,
    name: "Tardigrades",
    pokemon: "Pyukumuku",
    count: 1654,
  },
  {
    taxonId: 122158,
    name: "Brachiopods",
    pokemon: "Clamperl",
    count: 1425,
  },
  {
    taxonId: 48051,
    name: "Horseshoe Worms",
    pokemon: "Horsea",
    count: 628,
  },
  {
    taxonId: 151829,
    name: "Gastrotrichs",
    pokemon: "Trubbish",
    count: 625,
  },
  {
    taxonId: 211191,
    name: "Xenoturbellids & allies",
    pokemon: "Sandygast",
    count: 411,
  },
  {
    taxonId: 68235,
    name: "Hemichordates",
    pokemon: "Gastrodon",
    count: 288,
  },
  {
    taxonId: 151831,
    name: "Entoprocts",
    pokemon: "Probopass",
    count: 258,
  },
  {
    taxonId: 151827,
    name: "Arrow Worms",
    pokemon: "Beedrill",
    count: 140,
  },
  {
    taxonId: 151826,
    name: "Thorny-headed Worms",
    pokemon: "Weedle",
    count: 58,
  },
  {
    taxonId: 151838,
    name: "Priapulid Worms",
    pokemon: "Wurmple",
    count: 31,
  },
  {
    taxonId: 151832,
    name: "Mud Dragons",
    pokemon: "Gible",
    count: 15,
  },
  {
    taxonId: 151830,
    name: "Jaw Worms",
    pokemon: "Carvanha",
    count: 5,
  },
  {
    taxonId: 151837,
    name: "Placozoans",
    pokemon: "Ditto",
    count: 2,
  },
  {
    taxonId: 774624,
    name: "Dicyemids",
    pokemon: "Deoxys",
    count: 2,
  },
  {
    taxonId: 151836,
    name: "Orthonectids",
    pokemon: "Nincada",
    count: 1,
  },
  {
    taxonId: 151833,
    name: "Loriciferans",
    pokemon: "Shelmet",
    count: 0,
  },
  {
    taxonId: 884506,
    name: "Gnathiferans",
    pokemon: "Gnath",
    count: 0,
  },
  {
    taxonId: 151828,
    name: "Cycliophorans",
    pokemon: "Spinda",
    count: 0,
  },
]
